version: '3.7'

volumes:
    logs:
        driver: local

services:
    slim:
        image: php:7-alpine
        working_dir: /var/www
        command: php -S 0.0.0.0:8090 -t public
        environment:
            docker: "true"
        ports:
            - 8090:8090
        volumes:
            - .:/var/www
            - logs:/var/www/logs
